payload:
  - 'aboutfacebook.com'
  - 'accountkit.com'
  - 'atlasdmt.com'
  - 'buck.build'
  - 'crowdtangle.com'
  - 'dotfacebook.com'
  - 'expresswifi.com'
  - 'f8.com'
  - 'facebook.com'
  - 'facebook.net'
  - 'facebook.org'
  - 'facebookmail.com'
  - 'fasttext.cc'
  - 'fb.com'
  - 'fb.me'
  - 'fbcdn-a.akamaihd.net'
  - 'fbinfer.com'
  - 'fbworkmail.com'
  - 'flow.org'
  - 'freebasics.com'
  - 'ig.me'
  - 'instagr.am'
  - 'instagram.com'
  - 'internet.org'
  - 'm.me'
  - 'messenger.com'
  - 'meta.com'
  - 'ocul.us'
  - 'oculus.com'
  - 'ogp.me'
  - 'parse.com'
  - 'react.com'
  - 'reactjs.com'
  - 'recoiljs.org'
  - 'rocksdb.org'
  - 'terragraph.com'
  - 'thefacebook.com'
  - 'wa.me'
  - 'whatsapp.com'
  - 'whatsapp.net'
  - 'workplace.com'
  - 'threads.com'
  - 'threads.net'
